makefile = { declaration | comment | if_block | include_stmt }* ;

NEWLINE = '\n' ;

comment = /^#.*$/ ;

declaration = var_declaration | target_declaration;

var_declaration = var_name assignment var_value;

target_declaration = target_name colon '\n'.{ target_body };

var_name = /^[A-Z0-9a-z_]+/ ;

assignment = '=' | '+=' | '?=' | '!=' | ':=' ;

#var_value = '\\\n'.{ /!(\\)*/ } ;
var_value = '\\\n'.{?/\s*[ A-Za-z":0-9_.@,=|%'${}()/-]+/?} ;

target_name = /^[.\-A-Za-z]+/ ;

colon = ':' ;
newline = '\n' ;

target_body = '\n'.{ /^\s+.+/ };

if_block = '.if' if_condition if_body '.endif';

if_condition = ( '||' | '&&' ).{ subcondition };

subcondition = /.*/;

if_body = '\n'.{ /^\s*.+/ };

include_stmt = '.include' '<' '.'.{ /[a-z]+/ } '>' ;
